"""
Pydantic Schemas 模块
"""

from .points import (
    UserPointsResponse,
    PointTransactionResponse,
    PointTransactionCreate,
    PointsHistoryResponse,
)

from .team import (
    TeamCreate,
    TeamUpdate,
    TeamResponse,
    TeamDetailResponse,
    TeamListResponse,
    TeamMemberJoinRequest,
    TeamMemberResponse,
    TeamMemberDetailResponse,
    TeamMemberListResponse,
    TeamMemberUpdateRole,
    TeamMemberApproval,
    TeamTaskCreate,
    TeamTaskUpdate,
    TeamTaskResponse,
    TeamTaskListResponse,
    TeamLeaderboardResponse,
    TeamStatistics,
)

from .task import (
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    TaskListResponse,
    UserTaskCreate,
    UserTaskProgress,
    UserTaskClaim,
    UserTaskResponse,
    UserTaskDetailResponse,
    UserTaskListResponse,
    TaskStatistics,
    UserTaskSummary,
    TaskTypeStatistics,
)

from .quiz import (
    QuestionCreate,
    QuestionUpdate,
    QuestionReview,
    QuestionResponse,
    QuestionDetailResponse,
    QuestionListResponse,
    AnswerSubmit,
    AnswerResult,
    UserAnswerResponse,
    UserAnswerDetailResponse,
    UserAnswerListResponse,
    DailyQuizSessionResponse,
    QuizStatistics,
    CategoryStatistics,
    DifficultyStatistics,
    QuizRankingItem,
    QuizRankingResponse,
)

from .user import (
    UserRegisterRequest,
    UserResponse,
    UserDetailResponse,
    UserUpdateRequest,
    UserByWalletResponse,
)

__all__ = [
    # Points
    "UserPointsResponse",
    "PointTransactionResponse",
    "PointTransactionCreate",
    "PointsHistoryResponse",
    # Teams
    "TeamCreate",
    "TeamUpdate",
    "TeamResponse",
    "TeamDetailResponse",
    "TeamListResponse",
    "TeamMemberJoinRequest",
    "TeamMemberResponse",
    "TeamMemberDetailResponse",
    "TeamMemberListResponse",
    "TeamMemberUpdateRole",
    "TeamMemberApproval",
    "TeamTaskCreate",
    "TeamTaskUpdate",
    "TeamTaskResponse",
    "TeamTaskListResponse",
    "TeamLeaderboardResponse",
    "TeamStatistics",
    # Tasks
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    "UserTaskCreate",
    "UserTaskProgress",
    "UserTaskClaim",
    "UserTaskResponse",
    "UserTaskDetailResponse",
    "UserTaskListResponse",
    "TaskStatistics",
    "UserTaskSummary",
    "TaskTypeStatistics",
    # Quiz
    "QuestionCreate",
    "QuestionUpdate",
    "QuestionReview",
    "QuestionResponse",
    "QuestionDetailResponse",
    "QuestionListResponse",
    "AnswerSubmit",
    "AnswerResult",
    "UserAnswerResponse",
    "UserAnswerDetailResponse",
    "UserAnswerListResponse",
    "DailyQuizSessionResponse",
    "QuizStatistics",
    "CategoryStatistics",
    "DifficultyStatistics",
    "QuizRankingItem",
    "QuizRankingResponse",
    # Users
    "UserRegisterRequest",
    "UserResponse",
    "UserDetailResponse",
    "UserUpdateRequest",
    "UserByWalletResponse",
]
